# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.govt.example.com:
  peer0.ngo.example.com:
  peer0.univ.example.com:
  peer0.pvtbodies.example.com:
  peer0.public.example.com:
  cagovt:
  cango:
  cauniv:
  capvtbodies:
  capublic:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.govt.example.com:
    container_name: peer0.govt.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.govt.example.com
    networks:
      - byfn

  peer0.ngo.example.com:
    container_name: peer0.ngo.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ngo.example.com
    networks:
      - byfn

  peer0.univ.example.com:
    container_name: peer0.univ.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.univ.example.com
    networks:
      - byfn

  peer0.pvtbodies.example.com:
    container_name: peer0.pvtbodies.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.pvtbodies.example.com
    networks:
      - byfn

  peer0.public.example.com:
    container_name: peer0.public.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.public.example.com
    networks:
      - byfn

  cagovt:
    container_name: cagovt
    extends:
      file:  base/docker-compose-base.yaml
      service: cagovt
    networks:
      - byfn

  cango:
    container_name: cango
    extends:
      file:  base/docker-compose-base.yaml
      service: cango
    networks:
      - byfn

  cauniv:
    container_name: cauniv
    extends:
      file:  base/docker-compose-base.yaml
      service: cauniv
    networks:
      - byfn
  
  capvtbodies:
    container_name: capvtbodies
    extends:
      file:  base/docker-compose-base.yaml
      service: capvtbodies
    networks:
      - byfn

  capublic:
    container_name: capublic
    extends:
      file:  base/docker-compose-base.yaml
      service: capublic
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.govt.example.com:7051
      - CORE_PEER_LOCALMSPID=govtMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/govt.example.com/peers/peer0.govt.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/govt.example.com/peers/peer0.govt.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/govt.example.com/peers/peer0.govt.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/govt.example.com/users/Admin@govt.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.govt.example.com
      - peer0.ngo.example.com
      - peer0.univ.example.com
      - peer0.pvtbodies.example.com
      - peer0.public.example.com
      - cagovt
      - cango
      - cauniv
      - capvtbodies
      - capublic
    networks:
      - byfn
