# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.govt.example.com:
    container_name: peer0.govt.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.govt.example.com
      - CORE_PEER_ADDRESS=peer0.govt.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.govt.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.govt.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.govt.example.com:7051
      - CORE_PEER_LOCALMSPID=govtMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/govt.example.com/peers/peer0.govt.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/govt.example.com/peers/peer0.govt.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.govt.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.ngo.example.com:
    container_name: peer0.ngo.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ngo.example.com
      - CORE_PEER_ADDRESS=peer0.ngo.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ngo.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ngo.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ngo.example.com:7051
      - CORE_PEER_LOCALMSPID=ngoMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ngo.example.com/peers/peer0.ngo.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ngo.example.com/peers/peer0.ngo.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ngo.example.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.univ.example.com:
    container_name: peer0.univ.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.univ.example.com
      - CORE_PEER_ADDRESS=peer0.univ.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.univ.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.univ.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.univ.example.com:7051
      - CORE_PEER_LOCALMSPID=univMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/univ.example.com/peers/peer0.univ.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/univ.example.com/peers/peer0.univ.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.univ.example.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer0.pvtbodies.example.com:
    container_name: peer0.pvtbodies.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.pvtbodies.example.com
      - CORE_PEER_ADDRESS=peer0.pvtbodies.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pvtbodies.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pvtbodies.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pvtbodies.example.com:7051
      - CORE_PEER_LOCALMSPID=pvtbodiesMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pvtbodies.example.com/peers/peer0.pvtbodies.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pvtbodies.example.com/peers/peer0.pvtbodies.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pvtbodies.example.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.public.example.com:
    container_name: peer0.public.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.public.example.com
      - CORE_PEER_ADDRESS=peer0.public.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.public.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.public.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.public.example.com:7051
      - CORE_PEER_LOCALMSPID=publicMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/public.example.com/peers/peer0.public.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/public.example.com/peers/peer0.public.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.public.example.com:/var/hyperledger/production
    ports:
      - 11051:11051

  cagovt:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-govt
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.govt.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.govt.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/govt.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  cango:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ngo
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ngo.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ngo.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/ngo.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  cauniv:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-univ
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.univ.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.univ.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/univ.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  capvtbodies:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-pvtbodies
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pvtbodies.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.pvtbodies.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/pvtbodies.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  capublic:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-public
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.public.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.public.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/public.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
